apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=600
    - rsize=1048576
    - wsize=1048576
    - resvport
    - retrans=3
  capacity:
    storage: 20Gi
  nfs:
    server: 10.222.0.100 
    path: "/test"
  persistentVolumeReclaimPolicy: "Recycle"
