apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: "pv-test"
  storageClassName: ""
